version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "27018:27017"

  api:
    build: .
    container_name: cover-letter-ai-api
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017

volumes:
  mongodb_data:
