version: '3'

tasks:
  stop:
    desc: stop application services
    cmds:
      - docker compose --file=docker-compose.yml down
  run:
    desc: start application services
    cmds:
      - docker compose --file=docker-compose.yml up -d --build
  dev:
    desc: run dev environment
    cmds:
      - docker compose --file=docker-compose.yml up -d --build --quiet-pull mongodb
      - go run ./cmd/api
  test:
    desc: run application tests
    cmds:
      - docker compose --file=docker-compose-test.yml up -d --quiet-pull
      - go test ./...
      - docker compose --file=docker-compose-test.yml down
  mock:
    desc: generate mocks using gomock
    cmds:
      - go generate ./...
