// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jonada182/cover-letter-ai-api/internal/handler (interfaces: HandlerInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	types "github.com/jonada182/cover-letter-ai-api/types"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlerInterface is a mock of HandlerInterface interface.
type MockHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerInterfaceMockRecorder
}

// MockHandlerInterfaceMockRecorder is the mock recorder for MockHandlerInterface.
type MockHandlerInterfaceMockRecorder struct {
	mock *MockHandlerInterface
}

// NewMockHandlerInterface creates a new mock instance.
func NewMockHandlerInterface(ctrl *gomock.Controller) *MockHandlerInterface {
	mock := &MockHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerInterface) EXPECT() *MockHandlerInterfaceMockRecorder {
	return m.recorder
}

// HandleCoverLetter mocks base method.
func (m *MockHandlerInterface) HandleCoverLetter(arg0 *gin.Context, arg1 types.StoreClient, arg2 types.OpenAIClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCoverLetter", arg0, arg1, arg2)
}

// HandleCoverLetter indicates an expected call of HandleCoverLetter.
func (mr *MockHandlerInterfaceMockRecorder) HandleCoverLetter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCoverLetter", reflect.TypeOf((*MockHandlerInterface)(nil).HandleCoverLetter), arg0, arg1, arg2)
}

// HandleCreateCareerProfile mocks base method.
func (m *MockHandlerInterface) HandleCreateCareerProfile(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCreateCareerProfile", arg0)
}

// HandleCreateCareerProfile indicates an expected call of HandleCreateCareerProfile.
func (mr *MockHandlerInterfaceMockRecorder) HandleCreateCareerProfile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreateCareerProfile", reflect.TypeOf((*MockHandlerInterface)(nil).HandleCreateCareerProfile), arg0)
}

// HandleCreateJobApplication mocks base method.
func (m *MockHandlerInterface) HandleCreateJobApplication(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCreateJobApplication", arg0)
}

// HandleCreateJobApplication indicates an expected call of HandleCreateJobApplication.
func (mr *MockHandlerInterfaceMockRecorder) HandleCreateJobApplication(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreateJobApplication", reflect.TypeOf((*MockHandlerInterface)(nil).HandleCreateJobApplication), arg0)
}

// HandleGetCareerProfile mocks base method.
func (m *MockHandlerInterface) HandleGetCareerProfile(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetCareerProfile", arg0)
}

// HandleGetCareerProfile indicates an expected call of HandleGetCareerProfile.
func (mr *MockHandlerInterfaceMockRecorder) HandleGetCareerProfile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetCareerProfile", reflect.TypeOf((*MockHandlerInterface)(nil).HandleGetCareerProfile), arg0)
}

// HandleGetJobApplications mocks base method.
func (m *MockHandlerInterface) HandleGetJobApplications(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetJobApplications", arg0)
}

// HandleGetJobApplications indicates an expected call of HandleGetJobApplications.
func (mr *MockHandlerInterfaceMockRecorder) HandleGetJobApplications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetJobApplications", reflect.TypeOf((*MockHandlerInterface)(nil).HandleGetJobApplications), arg0)
}

// HandleIndex mocks base method.
func (m *MockHandlerInterface) HandleIndex(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleIndex", arg0)
}

// HandleIndex indicates an expected call of HandleIndex.
func (mr *MockHandlerInterfaceMockRecorder) HandleIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleIndex", reflect.TypeOf((*MockHandlerInterface)(nil).HandleIndex), arg0)
}
